BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS pumps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name STRING NOT NULL,
    is_working INTEGER DEFAULT 0,   
    pressure REAL DEFAULT 0,
    runtime INTEGER DEFAULT 0,
    timestamp STRING DEFAULT CURRENT_TIMESTAMP,
    emergency_mode INT DEFAULT 0,
    pressure_alert INT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS users (
    id INTEGER UNIQUE,
    name STRING NOT NULL UNIQUE,    
    password STRING,
    telegram_id INTEGER
    );
COMMIT;
